### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.example.haircolor-2/lib/arm/libmediapipe_jni.so"...

### ISSUE THREAD

**Issue by Annonymous844** [PrinceP/mediapipe#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.haircolor, PID: 20321
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.example.haircolor-2/lib/arm/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.example.haircolor.LiveActivity.<clinit>(LiveActivity.java:65)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1090)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Annonymous844** [comment]
Device Moto G3

**Comment by PrinceP** [comment]
[#521](https://github.com/google/mediapipe/issues/521)

**Comment by Annonymous844** [comment]
Thank You So much:))
last one how can i save oputput in storage??

**Comment by Annonymous844** [comment]
Thank you so much:))
